\hypertarget{classurllib3_1_1exceptions_1_1ResponseError}{}\doxysection{urllib3.\+exceptions.\+Response\+Error Class Reference}
\label{classurllib3_1_1exceptions_1_1ResponseError}\index{urllib3.exceptions.ResponseError@{urllib3.exceptions.ResponseError}}


Inheritance diagram for urllib3.\+exceptions.\+Response\+Error\+:
% FIG 0


Collaboration diagram for urllib3.\+exceptions.\+Response\+Error\+:
% FIG 1
\doxysubsection*{Static Public Attributes}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{classurllib3_1_1exceptions_1_1ResponseError_a4cd9797bb05770d5fc1fe94455e71864}\label{classurllib3_1_1exceptions_1_1ResponseError_a4cd9797bb05770d5fc1fe94455e71864}} 
string {\bfseries GENERIC\+\_\+\+ERROR} = \char`\"{}too many error responses\char`\"{}
\item 
\mbox{\Hypertarget{classurllib3_1_1exceptions_1_1ResponseError_aa2e385e3a04cbf09f36d1732c5417336}\label{classurllib3_1_1exceptions_1_1ResponseError_aa2e385e3a04cbf09f36d1732c5417336}} 
string {\bfseries SPECIFIC\+\_\+\+ERROR} = \char`\"{}too many \{status\+\_\+code\} error responses\char`\"{}
\end{DoxyCompactItemize}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Used as a container for an error reason supplied in a MaxRetryError.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+10/site-\/packages/urllib3/exceptions.\+py\end{DoxyCompactItemize}
